### ISSUE TITLE
MOFTONEに追従したフルリニューアル

### ISSUE THREAD

**Issue by qrac** [qrac/iostone#4]
- [x] [カラーフォーマットをHSL化してフルリニューアル · Issue #8 · qrac/moftone](https://github.com/qrac/moftone/issues/8)
- [x] [デモサイトデータをリポジトリから分離 · Issue #9 · qrac/moftone](https://github.com/qrac/moftone/issues/9)
- [x] [デモサイトをNetlifyへ移行・ドメイン変更 · Issue #10 · qrac/moftone](https://github.com/qrac/moftone/issues/10)
- [x] [色コードをJSON出力 · Issue #11 · qrac/moftone](https://github.com/qrac/moftone/issues/11)
- [x] [スウォッチ生成の自動化 · Issue #12 · qrac/moftone](https://github.com/qrac/moftone/issues/12)
- [x] [Stylusファイル生成の自動化 · Issue #13 · qrac/moftone](https://github.com/qrac/moftone/issues/13)
